language: php 

php:
  - 5.2
  - 5.3
  - 5.4

notifications:
  email: false

env:
  - REPORT_EXIT_STATUS=1

#Compile
before_script:
    - ./travis/compile.sh

# Run PHPs run-tests.php 
script: NO_INTERACTION=0 make test
